### ISSUE TITLE
Crash on Android Oreo when previewing wallpaper with crop enabled

### ISSUE THREAD

**Issue by danimahardhika** [danimahardhika/candybar-library#105]
```gradle
Fatal Exception: java.lang.IllegalStateException: Only fullscreen activities can request orientation
       at android.os.Parcel.readException(Parcel.java:1950)
       at android.os.Parcel.readException(Parcel.java:1888)
       at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5675)
       at android.app.Activity.setRequestedOrientation(Activity.java:5739)
       at com.dm.wallpaper.board.activities.WallpaperBoardPreviewActivity$2.a(SourceFile:683)
       at com.h.a.b.d.a(SourceFile:265)
       at com.h.a.b.d.a(SourceFile:209)
       at com.h.a.b.d.a(SourceFile:410)
       at com.dm.wallpaper.board.activities.WallpaperBoardPreviewActivity.a(SourceFile:677)
       at com.dm.wallpaper.board.activities.WallpaperBoardPreviewActivity.a(SourceFile:99)
       at com.dm.wallpaper.board.activities.WallpaperBoardPreviewActivity$1.onTransitionEnd(SourceFile:234)
       at android.transition.Transition.end(Transition.java:1926)
       at android.transition.TransitionSet$TransitionSetListener.onTransitionEnd(TransitionSet.java:369)
```

**Comment by atcharatip9035** [comment]
Atcharatip9035@gmail.com​
