### ISSUE TITLE
[help] - WallpaperFragment

### ISSUE THREAD

**Issue by msay2** [danimahardhika/candybar-library#34]
Hello,It's been 2 or 4 days since, I have this problem `WallpaperFragment`

The problem is very simple ...

I use the cloud wallpaper on my project, everything works at an exepction near `wallpaperAdapter` never adapts to the `RecyclerView`

The `Toast` appears and tells me that it did not work

I post this message only because I really really need help

**Comment by danimahardhika** [comment]
Need a logcat and more explanation

**Comment by msay2** [comment]
Hello 

```Gradle
03-20 03:53:44.915 19018 19018 I   art com.msay2.ilion                          Late-enabling -Xcheck:jni
03-20 03:53:47.297 19018 19018 W   System com.msay2.ilion                       ClassLoader referenced unknown path: /data/app/com.msay2.ilion-2/lib/arm
03-20 03:53:47.434 19018 19018 W   ImageLoader com.msay2.ilion                  memoryCache() and memoryCacheSize() calls overlap each other
03-20 03:53:47.713 19018 19029 W   art com.msay2.ilion                          Suspending all threads took: 19.042ms
03-20 03:53:47.720 19018 19018 W   ImageLoader com.msay2.ilion                  diskCache(), diskCacheSize() and diskCacheFileCount calls overlap each other
03-20 03:53:47.728 19018 19029 I   art com.msay2.ilion                          Background sticky concurrent mark sweep GC freed 2813(161KB) AllocSpace objects, 0(0B) LOS objects, 53% free, 591KB/1284KB, paused 26.702ms total 293.640ms
03-20 03:53:47.958 19018 19018 W   art com.msay2.ilion                          Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
03-20 03:53:48.842 19018 19040 D   OpenGLRenderer com.msay2.ilion               Use EGL_SWAP_BEHAVIOR_PRESERVED: false
03-20 03:53:48.939 19018 19040 D   libEGL com.msay2.ilion                       loaded /system/lib/egl/libEGL_mali.so
03-20 03:53:48.972 19018 19040 D   libEGL com.msay2.ilion                       loaded /system/lib/egl/libGLESv1_CM_mali.so
03-20 03:53:49.039 19018 19040 D   libEGL com.msay2.ilion                       loaded /system/lib/egl/libGLESv2_mali.so
03-20 03:53:49.154 19018 19040 I   OpenGLRenderer com.msay2.ilion               Initialized EGL, version 1.4
03-20 03:53:52.646 19018 19029 W   art com.msay2.ilion                          Suspending all threads took: 13.488ms
03-20 03:53:52.667 19018 19029 I   art com.msay2.ilion                          Background sticky concurrent mark sweep GC freed 2498(261KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 3MB/3MB, paused 17.822ms total 286.407ms
03-20 03:53:52.860 19018 19029 I   art com.msay2.ilion                          Background partial concurrent mark sweep GC freed 436(28KB) AllocSpace objects, 1(20KB) LOS objects, 39% free, 3MB/6MB, paused 1.373ms total 187.408ms
03-20 03:53:54.291 19018 19018 I   Choreographer com.msay2.ilion                Skipped 63 frames!  The application may be doing too much work on its main thread.
03-20 03:54:00.325 19018 19018 E   RecyclerView com.msay2.ilion                 No adapter attached; skipping layout
03-20 03:54:00.568 19018 19059 W   System com.msay2.ilion                       ClassLoader referenced unknown path: /system/framework/tcmclient.jar
03-20 03:54:01.993 19018 19059 D   IlIon com.msay2.ilion                        com.bluelinelabs.logansquare.NoSuchMapperException: Class com.msay2.ilion.item_data.WallpaperJSON could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
03-20 03:54:01.993 19018 19059 D   IlIon com.msay2.ilion                        at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:304)
03-20 03:54:01.993 19018 19059 D   IlIon com.msay2.ilion                        at com.bluelinelabs.logansquare.LoganSquare.parse(LoganSquare.java:69)
03-20 03:54:01.993 19018 19059 D   IlIon com.msay2.ilion                        at com.msay2.ilion.FragmentImages$100000001.doInBackground(FragmentImages.java:176)
03-20 03:54:01.993 19018 19059 D   IlIon com.msay2.ilion                        at com.msay2.ilion.FragmentImages$100000001.doInBackground(FragmentImages.java)
03-20 03:54:01.993 19018 19059 D   IlIon com.msay2.ilion                        at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-20 03:54:01.993 19018 19059 D  
```

**Comment by danimahardhika** [comment]
This is the problem
```java
com.bluelinelabs.logansquare.NoSuchMapperException: Class com.msay2.ilion.item_data.WallpaperJSON could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
```

Try to clean project first

**Comment by msay2** [comment]
I just cleaned up my project, and I always get this:

![screenshot_20170320-054014](https://cloud.githubusercontent.com/assets/19941384/24089040/f672414c-0d31-11e7-9781-557c57cdfc18.png)


And my logCat still has not changed:

```Gradle
03-20 05:37:36.776 31015 31015 E   RecyclerView com.msay2.ilion                 No adapter attached; skipping layout
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        com.bluelinelabs.logansquare.NoSuchMapperException: Class com.msay2.ilion.item_data.WallpaperJSON could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:304)
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at com.bluelinelabs.logansquare.LoganSquare.parse(LoganSquare.java:69)
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at com.msay2.ilion.FragmentImages$100000001.doInBackground(FragmentImages.java:176)
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at com.msay2.ilion.FragmentImages$100000001.doInBackground(FragmentImages.java)
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-20 05:37:38.148 31015 31141 D   IlIon com.msay2.ilion                        at java.lang.Thread.run(Thread.java:818)
```

**Comment by danimahardhika** [comment]
What did you do in FragmentImages lines 176?

You need to learn how to use LoganSquare, make sure you setup correct json object for logansquare

**Comment by msay2** [comment]
```java
wallpapersJSON = LoganSquare.parse(stream, WallpaperJSON.class);
```

**Comment by danimahardhika** [comment]
Check `WallpaperJson.java` and make sure to add annotation @JsonObject for the class, [sample](https://github.com/bluelinelabs/LoganSquare/blob/development/docs/AnnotationsOnlyModel.md)

**Comment by msay2** [comment]
My `WallpaperJSON.java` : 

```java
import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;

import java.util.List;

@JsonObject
public class WallpaperJSON 
{
    @JsonField(name = "Wallpapers")
    public List<WallpaperJSON> getWalls;
	
    @JsonField(name = "name")
    public String name;

    @JsonField(name = "author")
    public String author;

    @JsonField(name = "url")
    public String url;

    @JsonField(name = "thumburl")
    public String thumbUrl;
}
```

**Comment by danimahardhika** [comment]
Try to clean project or if you build release apk using proguard make sure to add logansquare proguard config.

There's no problem with your JSON object class. Maybe the stream or something else.

**Comment by msay2** [comment]
It still does not work. Your `getWallpaper()` method is copied directly from your project to my project (I did a copy and paste, to avoid mistakes)I left a problem report on the repository (LoganSquare)
(In case)

**Comment by danimahardhika** [comment]
You should check your project again. Looks like you did wrong implementation, the library works just fine.

Check `build.gradle` make sure to include logansquare and android apt dependency

**Comment by msay2** [comment]
Hello,

I just found a solution for this last one, I had to start small periods of tests and everything works perfectly ( Thank you anyway for your help)...BUT...the "setRefreshLayoutListener ()" crashes my project.

Would there be a bug with this one (the SwipeRefresh...) ?

**Comment by danimahardhika** [comment]
Do you mean `setOnRefreshListener()`?

Probably you just did wrong implementation, see the logcat there will be an explanation why your app crashed

**Comment by msay2** [comment]
Yes, 

My LogCat :

```Gradle
03-22 08:40:29.236 2111 2111 D     AndroidRuntime com.msay2.ilion               Shutting down VM
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               FATAL EXCEPTION: main
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               Process: com.msay2.ilion, PID: 2111
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at com.msay2.ilion.FragmentImages$100000001.onPreExecute(FragmentImages.java:90)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.os.AsyncTask.execute(AsyncTask.java:551)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at com.msay2.ilion.FragmentImages.getWallpapers(FragmentImages.java:83)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at com.msay2.ilion.FragmentImages.access$1000011(FragmentImages.java)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at com.msay2.ilion.FragmentImages$100000000.onRefresh(FragmentImages.java:74)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.support.v4.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:187)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.support.v4.widget.CircleImageView.onAnimationEnd(CircleImageView.java:106)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:6104)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:16131)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:16190)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15184)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:15957)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15179)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:15957)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15179)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:15957)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15179)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:15957)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1383)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:16190)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15184)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:15957)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15179)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:15957)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15179)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:15957)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15179)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:15957)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15179)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:15957)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.draw(View.java:16190)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2946)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.View.updateDisplayListIfDirty(View.java:15184)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewRootImpl.draw(ViewRootImpl.java:2623)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
03-22 08:40:29.508 2111 2111 E     AndroidRuntime com.msay2.ilion               at android.view.ViewRootImpl.doTraver
```

**Comment by msay2** [comment]
My onActivityCreated()

```java
@Override
	public void onActivityCreated(Bundle savedInstanceState)
	{
		super.onActivityCreated(savedInstanceState);
		
		recycler.setLayoutManager(new GridLayoutManager(getActivity(), 2));
		recycler.setItemAnimator(new DefaultItemAnimator());
		
		refresh.setColorSchemeColors(ContextCompat.getColor(getActivity(), R.color.accent));
		refresh.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener()
		{
			@Override
			public void onRefresh()
			{
				getWallpapers(true);
			}
		});

		getWallpapers(false);
	}
```

My void getWallpapers()
```java
private void getWallpapers(final boolean aBoolean)
	{
		mGetWallpapers = new AsyncTask<String, Void, Integer>()
		{
			@Override
			protected void onPreExecute() 
			{
				if (aBoolean)
				{
					progress.setVisibility(View.VISIBLE);
				}
				else
				{
					refresh.setRefreshing(true);
				}
			}

			@Override
			protected Integer doInBackground(String... params)
			{
				Integer result = 0;
				HttpURLConnection urlConnection;
				try
				{
					URL url = new URL("https://raw.githubusercontent.com/msay2/IlIon_wallpapers_json/master/ilion_wallpaper.json");
					urlConnection = (HttpURLConnection) url.openConnection();
					int statusCode = urlConnection.getResponseCode();

					// 200 represents HTTP OK
					if (statusCode == 200)
					{
						BufferedReader r = new BufferedReader(new InputStreamReader(urlConnection.getInputStream()));
						StringBuilder response = new StringBuilder();
						String line;

						while ((line = r.readLine()) != null)
						{
							response.append(line);
						}
						parseResult(response.toString());
						result = 1; // Successful
					}
					
					else 
					{
						result = 0; //"Failed to fetch data!";
					}
				} 
				catch (Exception e)
				{
					Log.d(TAG, e.getLocalizedMessage());
				}
				return result; //"Failed to fetch data!";
			}

			@Override
			protected void onPostExecute(Integer result)
			{
				if (aBoolean)
				{
					progress.setVisibility(View.GONE);
				}
				else
				{
					refresh.setRefreshing(false);
				}
				refresh.setRefreshing(false);
				
				if (result == 1) 
				{
					adapter = new AdapterImages(getActivity(), itemsData);
					recycler.setAdapter(adapter);
				} 
				else 
				{
					Toast.makeText(getActivity(), "Failed to fetch data!", Toast.LENGTH_SHORT).show();
				}
			}
		}.execute();
	}
```

**Comment by danimahardhika** [comment]
Learn how to read the logcat, this is the problem
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
```

Your `progress` is null, make sure to init it inside `onCreateView()` if you are using fragment

**Comment by msay2** [comment]
@danimahardhika

😒 Sure enough, I was mistaken in identification (findViewById).

Otherwise, apart from this small (flawed) error on my part, everything works perfectly.

Thank you thank you dani ✌🤓
