### ISSUE TITLE
Icon Request Issue: cannot jump to mail client

### ISSUE THREAD

**Issue by antoniacrespoa2** [danimahardhika/candybar-library#96]
### After select a mail client in the Icon Request section, nothing happened..

> Manufacturer: Sony
> Model: F8332
> Screen Resolution: 1920 x 1080 pixels
> Android Version: 7.1.1
> Candy Bar Version: 3.4.0

Here is the log
```

09-26 18:49:13.451 17272-17272/com.yeyebbc.meeye.iconpack I/System.out: waiting for debugger to settle...


09-26 18:49:13.652 17272-17272/com.yeyebbc.meeye.iconpack I/System.out: waiting for debugger to settle...
09-26 18:49:13.857 17272-17272/com.yeyebbc.meeye.iconpack I/System.out: debugger has settled (1424)
09-26 18:49:14.118 17272-17272/com.yeyebbc.meeye.iconpack W/System: ClassLoader referenced unknown path: /data/app/com.yeyebbc.meeye.iconpack-1/lib/arm64
09-26 18:49:14.193 17272-17272/com.yeyebbc.meeye.iconpack I/InstantRun: starting instant run server: is main process
09-26 18:49:14.236 17272-17272/com.yeyebbc.meeye.iconpack W/ImageLoader: diskCache(), diskCacheSize() and diskCacheFileCount calls overlap each other
09-26 18:49:14.439 17272-17272/com.yeyebbc.meeye.iconpack W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-26 18:49:14.761 17272-17502/com.yeyebbc.meeye.iconpack I/Adreno: QUALCOMM build                   : 49a2ab3, Ifedc5bd8d0
                                                                    Build Date                       : 12/15/16
                                                                    OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                                    Local Branch                     : 
                                                                    Remote Branch                    : 
                                                                    Remote Branch                    : 
                                                                    Reconstruct Branch               : 
09-26 18:49:14.778 17272-17502/com.yeyebbc.meeye.iconpack I/OpenGLRenderer: Initialized EGL, version 1.4
09-26 18:49:14.778 17272-17502/com.yeyebbc.meeye.iconpack D/OpenGLRenderer: Swap behavior 1
09-26 18:49:14.955 17272-17272/com.yeyebbc.meeye.iconpack I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@ec5217e time:348557170
09-26 18:49:15.061 17272-17272/com.yeyebbc.meeye.iconpack I/Timeline: Timeline: Activity_launch_request id:com.yeyebbc.meeye.iconpack time:348557276
09-26 18:49:15.225 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
09-26 18:49:15.226 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
09-26 18:49:15.226 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
09-26 18:49:15.230 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3ba7b84
09-26 18:49:15.231 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@420ff6d
09-26 18:49:15.231 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b2e27a2
09-26 18:49:15.232 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@c066c33
09-26 18:49:15.408 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b8efb72
09-26 18:49:15.409 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@8a9fbc3
09-26 18:49:15.591 17272-17515/com.yeyebbc.meeye.iconpack E/CandyBar: Appfilter Error
                                                                      Key: null
                                                                      Value: memrise
09-26 18:49:15.592 17272-17515/com.yeyebbc.meeye.iconpack E/CandyBar: Appfilter Error
                                                                      Key: null
                                                                      Value: netease_music
09-26 18:49:15.617 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@1059625
09-26 18:49:15.617 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@8be63fa
09-26 18:49:15.659 17272-17276/com.yeyebbc.meeye.iconpack I/art: Do partial code cache collection, code=23KB, data=29KB
09-26 18:49:15.687 17272-17283/com.yeyebbc.meeye.iconpack I/art: Background partial concurrent mark sweep GC freed 2974(432KB) AllocSpace objects, 6(168KB) LOS objects, 40% free, 8MB/14MB, paused 1.263ms total 114.140ms
09-26 18:49:15.689 17272-17276/com.yeyebbc.meeye.iconpack I/art: After code cache collection, code=23KB, data=29KB
09-26 18:49:15.689 17272-17276/com.yeyebbc.meeye.iconpack I/art: Increasing code cache capacity to 128KB
09-26 18:49:15.811 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@85611ae
09-26 18:49:15.811 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9cbb4f
09-26 18:49:15.818 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2d06fe5
09-26 18:49:15.818 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@4f59aba
09-26 18:49:15.961 17272-17276/com.yeyebbc.meeye.iconpack I/art: Do partial code cache collection, code=62KB, data=59KB
09-26 18:49:15.962 17272-17276/com.yeyebbc.meeye.iconpack I/art: After code cache collection, code=62KB, data=59KB
09-26 18:49:15.962 17272-17276/com.yeyebbc.meeye.iconpack I/art: Increasing code cache capacity to 256KB
09-26 18:49:16.090 17272-17276/com.yeyebbc.meeye.iconpack I/art: Compiler allocated 7MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
09-26 18:49:16.430 17272-17276/com.yeyebbc.meeye.iconpack I/art: Do full code cache collection, code=120KB, data=107KB
09-26 18:49:16.431 17272-17276/com.yeyebbc.meeye.iconpack I/art: Starting a blocking GC JitCodeCache
09-26 18:49:16.431 17272-17276/com.yeyebbc.meeye.iconpack I/art: After code cache collection, code=90KB, data=67KB
09-26 18:49:16.509 17272-17276/com.yeyebbc.meeye.iconpack I/art: Do partial code cache collection, code=96KB, data=85KB
09-26 18:49:16.509 17272-17276/com.yeyebbc.meeye.iconpack I/art: After code cache collection, code=96KB, data=85KB
09-26 18:49:16.509 17272-17276/com.yeyebbc.meeye.iconpack I/art: Increasing code cache capacity to 512KB
09-26 18:49:17.034 17272-17272/com.yeyebbc.meeye.iconpack W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
09-26 18:49:17.194 17272-17272/com.yeyebbc.meeye.iconpack I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@fb0460 time:348559409
09-26 18:49:18.310 17272-17272/com.yeyebbc.meeye.iconpack I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@fb0460 time:348560525
09-26 18:49:19.125 17272-17515/com.yeyebbc.meeye.iconpack W/System: ClassLoader referenced unknown path: 
09-26 18:49:19.127 17272-17515/com.yeyebbc.meeye.iconpack D/ApplicationLoaders: ignored Vulkan layer search path /data/app/com.wanmonstar.nokiaevolveplus-1/lib/arm:/data/app/com.wanmonstar.nokiaevolveplus-1/base.apk!/lib/armeabi-v7a for namespace 0x7faaad9160
09-26 18:49:19.492 17272-17276/com.yeyebbc.meeye.iconpack I/art: Do full code cache collection, code=252KB, data=214KB
09-26 18:49:19.493 17272-17276/com.yeyebbc.meeye.iconpack I/art: Starting a blocking GC JitCodeCache
09-26 18:49:19.493 17272-17276/com.yeyebbc.meeye.iconpack I/art: After code cache collection, code=219KB, data=158KB
09-26 18:49:20.468 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@d22cb8d
09-26 18:49:21.553 17272-17276/com.yeyebbc.meeye.iconpack I/art: Do partial code cache collection, code=251KB, data=199KB
09-26 18:49:21.555 17272-17276/com.yeyebbc.meeye.iconpack I/art: After code cache collection, code=245KB, data=194KB
09-26 18:49:21.555 17272-17276/com.yeyebbc.meeye.iconpack I/art: Increasing code cache capacity to 1024KB
09-26 18:49:21.764 17272-17276/com.yeyebbc.meeye.iconpack I/art: Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()
09-26 18:49:26.246 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@79f077
09-26 18:49:26.247 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@e39d4e4
09-26 18:49:26.320 17272-17272/com.yeyebbc.meeye.iconpack E/RecyclerView: No adapter attached; skipping layout
09-26 18:49:26.392 17272-17272/com.yeyebbc.meeye.iconpack I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
09-26 18:49:26.789 17272-17279/com.yeyebbc.meeye.iconpack W/art: Suspending all threads took: 7.334ms
09-26 18:49:31.046 17272-17272/com.yeyebbc.meeye.iconpack W/PropertyValuesHolder: Method set() with type float not found on target class class me.zhanghai.android.materialprogressbar.IndeterminateHorizontalProgressDrawable$RectTransformX
09-26 18:49:31.182 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@8b6d139
09-26 18:49:31.182 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@4aca37e
09-26 18:49:31.185 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@ac0f12c
09-26 18:49:31.185 17272-17272/com.yeyebbc.meeye.iconpack V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@1aa47f5
09-26 18:49:31.312 17272-17272/com.yeyebbc.meeye.iconpack W/art: Before Android 4.1, method android.graphics.drawable.Drawable me.zhanghai.android.materialprogressbar.MaterialProgressBar.getCurrentDrawable() would have incorrectly overridden the package-private method in android.widget.ProgressBar
09-26 18:49:32.144 17272-17502/com.yeyebbc.meeye.iconpack D/OpenGLRenderer: endAllActiveAnimators on 0x7f8dcf1400 (RippleDrawable) with handle 0x7f8e2e8a00
09-26 18:49:32.158 17272-17272/com.yeyebbc.meeye.iconpack E/CandyBar: java.lang.ClassCastException: java.lang.ref.WeakReference cannot be cast to com.dm.material.dashboard.candybar.utils.listeners.RequestListener
                                                                          at com.dm.material.dashboard.candybar.tasks.IconRequestBuilderTask.onPostExecute(IconRequestBuilderTask.java:156)
                                                                          at com.dm.material.dashboard.candybar.tasks.IconRequestBuilderTask.onPostExecute(IconRequestBuilderTask.java:48)
                                                                          at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                          at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                          at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:241)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by danimahardhika** [comment]
My mistake, I will push new release in a few minutes
